id: A04543C80
title: Toh_151-The_Questions_of_Pratibhanamati-v2
type: translation
pechas:
- ICA59A99A
- IA6C16453
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-057-010
  eft-text-version: 1.1.9 2021
  title: Toh_151-The_Questions_of_Pratibhanamati-v2
alignment_to_base:
  ICA59A99A/880C: C7F2
  IA6C16453/3A55: C7F2
